name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore src/portfolio.api/portfolio.api.csproj

    - name: Build project
      run: dotnet publish src/portfolio.api/portfolio.api.csproj -c Release -o ./publish

    - name: Zip Lambda package
      run: |
        cd publish
        zip -r ../lambda-package.zip ./*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name portfolio-api --zip-file fileb://lambda-package.zip