name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package Lambda (Only index.mjs)
      run: |
        mkdir -p package
        cp src/lambdas/portfolio-redis-keep-alive/index.mjs package/
        cd package
        zip -r lambda.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-lambda-function-name \
          --zip-file fileb://package/lambda.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
